var age = 25;
age = true;
console.log(age);
age = "hello";
console.log(age);
age = { name: "Luigi" };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push("mario");
mixed.push(false);
console.log(mixed);
var ninja;
ninja = { name: "Youshi", age: 25 };
console.log(ninja);
ninja = { name: 24, age: "Sue" };
console.log(ninja);
